### ISSUE TITLE
Missing import line in first-hardware.md

### ISSUE THREAD

**Issue by PlazmaZero** [jlpteaching/dinocpu-wq22#1]
Missing:
```
import chisel3.iotesters.{ChiselFlatSpec, Driver, PeekPokeTester}
```
before simulating and testing the circuit. The code will not compile without the related libraries.

**Comment by powerjg** [comment]
@takekoputa, can you fix this? (also in the public version)

Thanks!

**Comment by hnpl** [comment]
Fixed.
